//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.17 at 01:42:47 PM ICT 
//


package com.example.demo.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="addParamGroup" type="{http://example.com/demo/ws}paramGroups"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addParamGroup"
})
@XmlRootElement(name = "addParamGroupRequest")
public class AddParamGroupRequest {

    @XmlElement(required = true)
    protected ParamGroups addParamGroup;

    /**
     * Gets the value of the addParamGroup property.
     * 
     * @return
     *     possible object is
     *     {@link ParamGroups }
     *     
     */
    public ParamGroups getAddParamGroup() {
        return addParamGroup;
    }

    /**
     * Sets the value of the addParamGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamGroups }
     *     
     */
    public void setAddParamGroup(ParamGroups value) {
        this.addParamGroup = value;
    }

}
