//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.17 at 01:42:47 PM ICT 
//


package com.example.demo.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="addParamInfo" type="{http://example.com/demo/ws}paramInfos"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addParamInfo"
})
@XmlRootElement(name = "addParamInfoRequest")
public class AddParamInfoRequest {

    @XmlElement(required = true)
    protected ParamInfos addParamInfo;

    /**
     * Gets the value of the addParamInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ParamInfos }
     *     
     */
    public ParamInfos getAddParamInfo() {
        return addParamInfo;
    }

    /**
     * Sets the value of the addParamInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamInfos }
     *     
     */
    public void setAddParamInfo(ParamInfos value) {
        this.addParamInfo = value;
    }

}
