//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.17 at 01:42:47 PM ICT 
//


package com.example.demo.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetParamInfoRequest }
     * 
     */
    public GetParamInfoRequest createGetParamInfoRequest() {
        return new GetParamInfoRequest();
    }

    /**
     * Create an instance of {@link GetParamInfoResponse }
     * 
     */
    public GetParamInfoResponse createGetParamInfoResponse() {
        return new GetParamInfoResponse();
    }

    /**
     * Create an instance of {@link ParamInfos }
     * 
     */
    public ParamInfos createParamInfos() {
        return new ParamInfos();
    }

    /**
     * Create an instance of {@link GetParamGroupRequest }
     * 
     */
    public GetParamGroupRequest createGetParamGroupRequest() {
        return new GetParamGroupRequest();
    }

    /**
     * Create an instance of {@link GetParamGroupResponse }
     * 
     */
    public GetParamGroupResponse createGetParamGroupResponse() {
        return new GetParamGroupResponse();
    }

    /**
     * Create an instance of {@link ParamGroups }
     * 
     */
    public ParamGroups createParamGroups() {
        return new ParamGroups();
    }

    /**
     * Create an instance of {@link GetAllParamGroupRequest }
     * 
     */
    public GetAllParamGroupRequest createGetAllParamGroupRequest() {
        return new GetAllParamGroupRequest();
    }

    /**
     * Create an instance of {@link GetAllParamGroupResponse }
     * 
     */
    public GetAllParamGroupResponse createGetAllParamGroupResponse() {
        return new GetAllParamGroupResponse();
    }

    /**
     * Create an instance of {@link DeleteParamGroupRequest }
     * 
     */
    public DeleteParamGroupRequest createDeleteParamGroupRequest() {
        return new DeleteParamGroupRequest();
    }

    /**
     * Create an instance of {@link DeleteParamGroupResponse }
     * 
     */
    public DeleteParamGroupResponse createDeleteParamGroupResponse() {
        return new DeleteParamGroupResponse();
    }

    /**
     * Create an instance of {@link DeleteParamInfoRequest }
     * 
     */
    public DeleteParamInfoRequest createDeleteParamInfoRequest() {
        return new DeleteParamInfoRequest();
    }

    /**
     * Create an instance of {@link DeleteParamInfoResponse }
     * 
     */
    public DeleteParamInfoResponse createDeleteParamInfoResponse() {
        return new DeleteParamInfoResponse();
    }

    /**
     * Create an instance of {@link AddParamGroupRequest }
     * 
     */
    public AddParamGroupRequest createAddParamGroupRequest() {
        return new AddParamGroupRequest();
    }

    /**
     * Create an instance of {@link AddParamGroupResponse }
     * 
     */
    public AddParamGroupResponse createAddParamGroupResponse() {
        return new AddParamGroupResponse();
    }

    /**
     * Create an instance of {@link AddParamInfoRequest }
     * 
     */
    public AddParamInfoRequest createAddParamInfoRequest() {
        return new AddParamInfoRequest();
    }

    /**
     * Create an instance of {@link AddParamInfoResponse }
     * 
     */
    public AddParamInfoResponse createAddParamInfoResponse() {
        return new AddParamInfoResponse();
    }

    /**
     * Create an instance of {@link UpdateParamGroupRequest }
     * 
     */
    public UpdateParamGroupRequest createUpdateParamGroupRequest() {
        return new UpdateParamGroupRequest();
    }

    /**
     * Create an instance of {@link UpdateParamGroupResponse }
     * 
     */
    public UpdateParamGroupResponse createUpdateParamGroupResponse() {
        return new UpdateParamGroupResponse();
    }

    /**
     * Create an instance of {@link UpdateParamInfoRequest }
     * 
     */
    public UpdateParamInfoRequest createUpdateParamInfoRequest() {
        return new UpdateParamInfoRequest();
    }

    /**
     * Create an instance of {@link UpdateParamInfoResponse }
     * 
     */
    public UpdateParamInfoResponse createUpdateParamInfoResponse() {
        return new UpdateParamInfoResponse();
    }

}
