//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.17 at 01:42:47 PM ICT 
//


package com.example.demo.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paramInfos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paramInfos"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="paramInfoId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="paramInfoName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isdeleted" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="paramGroupId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paramInfos", propOrder = {
    "paramInfoId",
    "paramInfoName",
    "isdeleted",
    "paramGroupId"
})
public class ParamInfos {

    protected int paramInfoId;
    @XmlElement(required = true)
    protected String paramInfoName;
    @XmlElement(required = true)
    protected String isdeleted;
    protected int paramGroupId;

    /**
     * Gets the value of the paramInfoId property.
     * 
     */
    public int getParamInfoId() {
        return paramInfoId;
    }

    /**
     * Sets the value of the paramInfoId property.
     * 
     */
    public void setParamInfoId(int value) {
        this.paramInfoId = value;
    }

    /**
     * Gets the value of the paramInfoName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamInfoName() {
        return paramInfoName;
    }

    /**
     * Sets the value of the paramInfoName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamInfoName(String value) {
        this.paramInfoName = value;
    }

    /**
     * Gets the value of the isdeleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * Sets the value of the isdeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsdeleted(String value) {
        this.isdeleted = value;
    }

    /**
     * Gets the value of the paramGroupId property.
     * 
     */
    public int getParamGroupId() {
        return paramGroupId;
    }

    /**
     * Sets the value of the paramGroupId property.
     * 
     */
    public void setParamGroupId(int value) {
        this.paramGroupId = value;
    }

}
