//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.17 at 01:42:47 PM ICT 
//


package com.example.demo.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for paramGroups complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paramGroups"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="paramGroupId" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="paramGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isdeleted" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paramGroups", propOrder = {
    "paramGroupId",
    "paramGroupName",
    "isdeleted"
})
public class ParamGroups {

    protected int paramGroupId;
    @XmlElement(required = true)
    protected String paramGroupName;
    @XmlElement(required = true)
    protected String isdeleted;

    /**
     * Gets the value of the paramGroupId property.
     * 
     */
    public int getParamGroupId() {
        return paramGroupId;
    }

    /**
     * Sets the value of the paramGroupId property.
     * 
     */
    public void setParamGroupId(int value) {
        this.paramGroupId = value;
    }

    /**
     * Gets the value of the paramGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParamGroupName() {
        return paramGroupName;
    }

    /**
     * Sets the value of the paramGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParamGroupName(String value) {
        this.paramGroupName = value;
    }

    /**
     * Gets the value of the isdeleted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * Sets the value of the isdeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsdeleted(String value) {
        this.isdeleted = value;
    }

}
